# .github/actions/discover-dockerfiles/action.yml
name: 'Discover Dockerfiles'
description: 'Discover Dockerfiles in a repository (and on one level subfolders) and return an array of elements found, to be used in a matrix.'

inputs:
  subfolders-levels:
    description: 'How many subfolder levels to search (e.g. 3)'
    required: false
    type: string
    default: "1"
  repository:
    description: 'Repository name (e.g. "Neomediatech/php")'
    required: false
    type: string
    default: ""

outputs:
  matrix:
    value: ${{ steps.set-matrix.outputs.matrix }}
  repo-lower:
    description: "Lowercase repository name"
    value: ${{ steps.set-matrix.outputs.repo-lower }}

runs:
  # Indica una Composite Action
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}

    - name: Find Dockerfiles and build paired matrix (and show it)
      id: set-matrix
      shell: bash
      run: |
        DEPTH=$[${{ inputs.subfolders-levels }}+1]
        files=$(find . -maxdepth $DEPTH -type f -name 'Dockerfile*' | sort -r)
        includes=""
        versions=""
        types=""

        IMAGE_VERSIONS="[]"

        while IFS= read -r file; do
          dir=$(dirname "$file" | sed 's|^\./||')
          dockerfile=$(basename "$file")
          if [[ $dockerfile == 'Dockerfile' ]]; then
            version='latest'
          else
            version=$(basename "$file"|sed 's/Dockerfile\.\?//')
          fi
          IMAGE_VERSIONS=$(echo "$IMAGE_VERSIONS" | jq -c --arg v "$version" --arg t "$dir" '. += [{"version": $v, "type": $t}]')
        done <<< "$files"
        echo "::notice::IMAGE_VERSIONS $IMAGE_VERSIONS"
        # Rimuove la virgola finale e crea array include

        echo "matrix=$IMAGE_VERSIONS" >> $GITHUB_OUTPUT
          
        REPO_LOWER="$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')"
        echo "repo-lower=$REPO_LOWER" >> $GITHUB_OUTPUT

        echo "matrix: $IMAGE_VERSIONS"
        echo "repo-lower: $REPO_LOWER"
