name: Build and Push Docker Image

on:
  workflow_dispatch: # Permette di avviare il workflow manualmente dalla UI di GitHub
  workflow_call: # Permette di riutilizzare il workflow da un altro repo
    inputs:
      dockerfile:
        description: 'Dockerfile name'
        required: false
        type: string
        default: "Dockerfile"
      dockerdir:
        description: 'Path for the Dockerfile'
        required: false
        type: string
        default: "."
      dockertag:
        description: 'Tag for the image'
        required: false
        type: string
        default: "latest"
      base_image_digest:
        description: 'Base image digest'
        required: false
        type: string
      
  #push:
  #  branches:
    secrets:
      GHCR_TOKEN:
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Permesso per il checkout del codice
      packages: write # Permesso per scrivere pacchetti (necessario per GHCR)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up image tag (lowercase)
        id: vars
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${REPO_LOWER}"|awk -F'/' '{print $2}')
          echo "tag=ghcr.io/${REPO_LOWER}:${{ inputs.dockertag }}" >> $GITHUB_OUTPUT
          echo "repo_name=${REPO_NAME}" >> $GITHUB_OUTPUT
          # recupero l'immagine di base dal Dockerfile
          BASE_IMAGE="$(cat ${{ inputs.dockerfile }}|grep ^FROM|awk '{print $2}')"
          echo "base_image=${BASE_IMAGE}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build --pull --label "org.opencontainers.image.base.digest=${{ inputs.base_image_digest }}" \
          --label "org.opencontainers.image.base=${{ steps.vars.outputs.base_image }}" \
          -t ${{ steps.vars.outputs.tag }} -f ${{ inputs.dockerdir }}/${{ inputs.dockerfile }} ${{ inputs.dockerdir }}/
            
      - name: Push Docker image to GHCR
        run: docker push ${{ steps.vars.outputs.tag }}

      - name: Set INPUT_IMAGE_REF
        run: echo "INPUT_IMAGE_REF=${{ steps.vars.outputs.tag }}" >> $GITHUB_ENV

#  get-base-image-info:
#    secrets: inherit
#    needs: [build-and-push]
#    uses: Neomediatech/gh-workflows/.github/workflows/get-base-image-info.yml@main
#    with:
#      repository: ${{ needs.build-and-push.repo_name }}
#      tag: ${{ inputs.dockertag }}
