name: Build and Scan Docker Image

on:
  workflow_dispatch: # Permette di avviare il workflow manualmente dalla UI di GitHub
  workflow_call: # Permette di riutilizzare il workflow da un altro repo
    inputs:
      dockerfile:
        description: 'Dockerfile name'
        required: false
        type: string
        default: "Dockerfile"
      dockerdir:
        description: 'Path for the Dockerfile'
        required: false
        type: string
        default: "."
      dockertag:
        description: 'Tag for the image'
        required: false
        type: string
        default: "latest"
      filename:
        required: false
        type: string
      file_id:
        required: false
        type: string
  #push:
  #  branches:
  #    - main # Esegui quando ci sono push sul branch main (o il tuo branch principale)
    secrets:
      GHCR_TOKEN:
        required: false
    outputs:
      file_to_copy_output:
        description: "The name of the generated HTML report file"
        value: ${{ jobs.build-and-scan.outputs.file_to_copy_output }}
      uploaded-file-id:
        description: "The artifact ID of the uploaded HTML report"
        value: ${{ jobs.build-and-scan.outputs.uploaded-file-id }}

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Permesso per il checkout del codice
      packages: write # Permesso per scrivere pacchetti (necessario per GHCR)
    outputs:
      # Define an output for this job
      file_to_copy_output: ${{ steps.vars.outputs.html_to_copy }}
      uploaded-file-id: ${{ steps.upload-step.outputs.artifact-id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up image tag (lowercase)
        id: vars
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${REPO_LOWER}"|awk -F'/' '{print $2}')
          echo "tag=ghcr.io/${REPO_LOWER}:${{ inputs.dockertag }}" >> $GITHUB_OUTPUT
          echo "repo_name=${REPO_NAME}" >> $GITHUB_OUTPUT
          echo "html_to_copy=${REPO_NAME}_${{ inputs.dockertag }}_trivy-report.html" >> $GITHUB_OUTPUT
          echo "json_to_copy=${REPO_NAME}_${{ inputs.dockertag }}_trivy-report.json" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ${{ steps.vars.outputs.tag }} ${{ inputs.dockerdir }} -f ${{ inputs.dockerdir }}/${{ inputs.dockerfile }}

      - name: Push Docker image to GHCR
        run: docker push ${{ steps.vars.outputs.tag }}

      - name: Set INPUT_IMAGE_REF
        run: echo "INPUT_IMAGE_REF=${{ steps.vars.outputs.tag }}" >> $GITHUB_ENV

      - name: Run Trivy vulnerability scanner and save JSON report
        uses: aquasecurity/trivy-action@0.30.0
        #run: trivy image --format json -o trivy-report.json --ignore-unfixed --vuln-type os,library --severity CRITICAL,HIGH $INPUT_IMAGE_REF
        with:
          #version: latest
          image-ref: ${{ steps.vars.outputs.tag }}
          format: 'json'
          output: ${{ steps.vars.outputs.json_to_copy }}
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        env:
          INPUT_IMAGE_REF: ${{ steps.vars.outputs.tag }}

      - name: Get the trivy HTML template
        run: wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl

      - name: Generate HTML report from JSON
        run: trivy convert --format template --template "@$GITHUB_WORKSPACE/html.tpl" -o ${{ steps.vars.outputs.html_to_copy }} ${{ steps.vars.outputs.json_to_copy }}

      - name: Upload json report
        id: upload-json
        uses: actions/upload-artifact@v4
        with:
          name: uploaded-json_${{ inputs.dockertag }}
          path: ${{ steps.vars.outputs.json_to_copy }}
          overwrite: true
          compression-level: 0
          retention-days: 1

      - name: Upload html report
        id: upload-step
        uses: actions/upload-artifact@v4
        with:
          name: uploaded-file_${{ inputs.dockertag }}
          path: ${{ steps.vars.outputs.html_to_copy }}
          overwrite: true
          compression-level: 0
          retention-days: 1

      # ToDo
      #- name: Fail if critical/high vulnerabilities found
      #  run: |
      #    jq '.Results[].Vulnerabilities[] | select(.Severity == "CRITICAL" or .Severity == "HIGH")' ${{ steps.vars.outputs.json_to_copy }} && exit 1 || exit 0

      #- name: Send email with Trivy report attached
      #  if: always()
      #  run: |
      #    echo "import smtplib" > send_email.py
      #    echo "import ssl" >> send_email.py
      #    echo "from email.message import EmailMessage" >> send_email.py
      #    echo "from pathlib import Path" >> send_email.py
      #    echo "" >> send_email.py
      #    echo "msg = EmailMessage()" >> send_email.py
      #    echo "msg['Subject'] = '📦 GitHub Actions - Build terminata: ${{ job.status }}'" >> send_email.py
      #    echo "msg['From'] = '${{ secrets.SMTP_FROM }}'" >> send_email.py
      #    echo "msg['To'] = '${{ secrets.SMTP_TO }}'" >> send_email.py
      #    echo "msg.set_content('''Il workflow del repository \"${{ github.repository }}\" è terminato con stato: ${{ job.status }}\n\n🔗 Azione: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\n\nCommit: ${{ github.sha }}\nAutore: ${{ github.actor }}\nJob: ${{ github.workflow }}''')" >> send_email.py
      #    echo "" >> send_email.py
      #    echo "report_path = Path('trivy-report.html')" >> send_email.py
      #    echo "if report_path.exists():" >> send_email.py
      #    echo "    with report_path.open('rb') as f:" >> send_email.py
      #    echo "        msg.add_attachment(f.read(), maintype='text', subtype='html', filename='trivy-report.html')" >> send_email.py
      #    echo "" >> send_email.py
      #    echo "context = ssl.create_default_context()" >> send_email.py
      #    echo "with smtplib.SMTP_SSL('${{ secrets.SMTP_HOST }}', int('${{ secrets.SMTP_PORT }}'), context=context) as smtp:" >> send_email.py
      #    # echo "    smtp.login('${{ secrets.SMTP_USER }}', '${{ secrets.SMTP_PASSWORD }}')" >> send_email.py
      #    echo "    smtp.send_message(msg)" >> send_email.py
      #    python3 send_email.py
