name: Delete old untagged Docker images

on:
  #schedule:
  #  - cron: '0 22 * * *' # ogni giorno alle 22:00 UTC
  workflow_dispatch:
    inputs:
      target-repo:
        description: 'Nome del repository da cui eliminare le immagini (es: ubuntu-base)'
        required: true
        default: 'ubuntu-base'
      package-name:
        description: 'Nome del package container (es: ubuntu-base)'
        required: true
        default: 'ubuntu-base'
  workflow_call:
    inputs:
      target-repo:
        description: 'Nome del repository da cui eliminare le immagini (es: ubuntu-base)'
        required: true
        type: string
        default: 'ubuntu-base'
      package-name:
        description: 'Nome del package container (es: ubuntu-base)'
        required: true
        type: string
        default: 'ubuntu-base'

jobs:
  delete-untagged-container-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged container versions from remote repo
        uses: actions/delete-package-versions@v5
        with:
          owner: Neomediatech
          repo: ${{ github.event.inputs.target-repo || inputs.target-repo || 'ubuntu-base' }}
          package-name: ${{ github.event.inputs.package-name || inputs.package-name || 'ubuntu-base' }}
          package-type: 'container'
          min-versions-to-keep: 2
          delete-only-untagged-versions: 'true'
          #token: ${{ secrets.PAT_WITH_DELETE_PACKAGES }}
