name: Check and Build Docker Images (by Copilot)

on:
  workflow_call:
    inputs:
      image-type:
        description: 'Image type choosen from below list (php,exim,rspamd,ssh,others)'
        required: true
        type: string
        default: "none"
      base-image:
        description: 'Image to use for executing commands (example: ubuntu:rolling)'
        required: true
        type: string
        default: "ubuntu:rolling"
      derived-image:
        description: 'Image to use for executing commands (example: ghcr.io/neomediatech/ubuntu-base:rolling)'
        required: true
        type: string
        default: "ghcr.io/neomediatech/ubuntu-base:rolling"

    outputs:
      exit-code:
        description: "Codice di uscita del workflow (per debug o eventuali utilizzi futuri)"
        value: ${{ jobs.job_1.outputs.exit-code }}
      image-res:
        description: "Risultato del comando eseguito"
        value: ${{ jobs.job_1.outputs.cmd-res }}

jobs:
  job_1:
    runs-on: [self-hosted]
    outputs:
      exit-code: ${{ steps.job_1_output.outputs.exit-code }}
      image-res: ${{ steps.job_1_output.outputs.cmd-res }}
    steps:
      - name: Generate an output
        id: job_1_output
        run: |
          echo "::notice::Questo è un output di esempio."
          echo "exit-code=99" >> $GITHUB_OUTPUT
          #  BASE_PACKAGE_VERSION="$(docker run --rm --entrypoint /bin/sh -u root $BASE_IMAGE -c "apt-get update 1>/dev/null ; apt-cache policy ${{ inputs.package-to-check }} |grep Candidat|awk '{print \$2}'")"
          DOCKER_CMD="docker run --rm --entrypoint /bin/sh -u root"

          case "${{ inputs.image-type }}" in
            "php")
              SHELL_ARGS="-c 'php -m|egrep -v \"^\[|^$\"|sort|uniq|grep -v Warning'"
              THIS_CMD="$DOCKER_CMD ${{ inputs.derived-image }} $SHELL_ARGS"
              echo "THIS_CMD: $THIS_CMD"
              DERIVED_MODULES="$($THIS_CMD)"
              echo "DERIVED_MODULES: $DERIVED_MODULES"
              echo "cmd-res=$DERIVED_MODULES" >> $GITHUB_OUTPUT
              ;;
            "exim")
              echo "exit-code=2" >> $GITHUB_OUTPUT
              echo "cmd-res=exim 4.98" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "default STATEMENT"
              ;;
          esac
