name: Proxmox Backup Server Check Image Updates and Rebuild

on:
  #schedule:
    # Esegui ogni giorno alle 04:00 UTC per controllare gli aggiornamenti.
  #  - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update-images:
    uses: Neomediatech/gh-workflows/.github/workflows/check-and-build-docker-images.yml@main
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      base-image: debian:bookworm
      derived-image-prefix: ghcr.io/neomediatech/pbs
      versions: '["latest", "3.4"]'
      #type: '["apache", "fpm"]'
      derived-image-repo: Neomediatech/pbs-docker
      derived-image-repo-ref: main
      update-image: "true"
      build-test-image: "false"
      package-name: "neomediatech/pbs"
