name: test
on:
  workflow_dispatch:

jobs:
  #one-job:
  #  runs-on: [self-hosted]
  #  strategy:
  #    matrix:
  #      version: ["ver1","ver2","ver3"]
  #      type: ["type1","type2","type3"]
  #    max-parallel: 1
  #  env:
  #    MASTER_REPO: "Neomediatech/gh-workflows.git"
  #  steps:
  #    - name: Set some var
  #      id: set-vars
  #      run: |
  #        echo "DERIVED_IMAGE=${{ matrix.version }}-${{ matrix.type }}" >> $GITHUB_ENV

  #    - name: Get some var
  #      id: get-vars
  #      run: |
  #        echo "DERIVED_IMAGE=$DERIVED_IMAGE"

  call_reusable_workflow:
    # Rimuovi completamente la riga 'runs-on: ubuntu-latest' da qui
    uses: Neomediatech/gh-workflows/.github/workflows/image-type-list.yml@main
    with:
      image-type: "exim"

  use_reusable_workflow_outputs:
    runs-on: [self-hosted]
    needs: call_reusable_workflow
    steps:
      - name: Print output from reusable workflow
        run: |
          echo "Output from reusable workflow: ${{ needs.call_reusable_workflow.outputs.exit-code }}"
