name: Ubuntu Check Image Updates and Rebuild

on:
  schedule:
    # Esegui ogni giorno alle 04:00 UTC per controllare gli aggiornamenti.
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update-images:
    uses: Neomediatech/gh-workflows/.github/workflows/check-and-build-docker-images.yml@main
    permissions:
      contents: write
      packages: write
      actions: write
    secrets: inherit
    with:
      base-image: ubuntu
      derived-image-prefix: ghcr.io/neomediatech/ubuntu-base
      versions: '["latest", "24.04", "22.04", "20.04", "18.04"]'
      #type: '["apache", "fpm"]'
      derived-image-repo: Neomediatech/ubuntu-base
      derived-image-repo-ref: master
      update-image: "true"
      build-test-image: "false"
